# permissions for end users to view federatedclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: federatedcluster-viewer-role
rules:
- apiGroups:
  - federation.example.com
  resources:
  - federatedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - federation.example.com
  resources:
  - federatedclusters/status
  verbs:
  - get
