---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - federation.example.com
  resources:
  - federatedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - federation.example.com
  resources:
  - federatedclusters/finalizers
  verbs:
  - update
- apiGroups:
  - federation.example.com
  resources:
  - federatedclusters/status
  verbs:
  - get
  - patch
  - update
